// 由 dev/build_site_data.py 生成，请勿手改；改内容请改 dev/style-master.json
window.STYLE_DATA = {
 "video": {
  "bvid": "BV1anQwYZEw2",
  "title": "你一直在寻找的 40 种设计风格名称（更快地找到参考）",
  "up": "咲喜",
  "url": "https://www.bilibili.com/video/BV1anQwYZEw2",
  "duration": 1855,
  "lang": "原视频为英文，本条为中文搬运；风格名以视频标题卡为准",
  "subtitle": {
   "lan": "zh-Hans",
   "lanDoc": "中文（简体）",
   "author": "咲喜（上传者本人制作，非 AI 转写）",
   "lines": 484,
   "aiType": 0
  }
 },
 "groups": [
  {
   "id": "classical",
   "zh": "古典与装饰",
   "desc": "从历史装饰语汇里取材：秩序、曲线、金属与繁复。"
  },
  {
   "id": "painting",
   "zh": "绘画与拼贴",
   "desc": "以画面本身说话：笔触、光影、材料与梦。"
  },
  {
   "id": "modern",
   "zh": "现代主义与平面",
   "desc": "给平面设计用的语言：网格、几何、排版与克制。"
  },
  {
   "id": "digital",
   "zh": "数字与街头",
   "desc": "屏幕与街道长出来的美学：像素、霓虹、喷漆。"
  },
  {
   "id": "soft",
   "zh": "柔光与生活",
   "desc": "关于氛围与生活方式：光、材质、柔软与克制。"
  },
  {
   "id": "bonus",
   "zh": "视频加映",
   "desc": "视频结尾额外给的一种风格。"
  }
 ],
 "styles": [
  {
   "slug": "neoclassical",
   "en": "Neoclassical",
   "zh": "新古典主义",
   "group": "classical",
   "t": 51,
   "tc": "0:51",
   "desc": "从古希腊罗马的秩序里取形：严格对称、柱式与三角楣、大理石白与赭石，配古典衬线体。用来表达权威、传承与庄重。",
   "traits": [
    "严格对称",
    "柱式·三角楣",
    "大理石白·赭石",
    "古典衬线"
   ],
   "img": "img/neoclassical.jpg",
   "thumb": "img/thumbs/neoclassical.jpg",
   "accent": "#8c665b",
   "accentInk": "#6b524b",
   "tint": "#1d1817",
   "tintLight": "#f1d9d2",
   "lum": 0.513,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=51",
   "videoName": "NEOCLASSICAL ART",
   "ref": {
    "img": "img/pd/neoclassical.jpg",
    "title": "Museo Correr Neoclassical ceiling 03032015 4.jpg",
    "artist": "Vassil",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "page": "https://commons.wikimedia.org/wiki/File:Museo_Correr_Neoclassical_ceiling_03032015_4.jpg",
    "w": 1400,
    "h": 939,
    "bytes": 324335
   },
   "say": "这里的一切基本上都是对古希腊的致敬——当你看到那些画作时，立刻会想到米开朗基罗的《创世纪》。",
   "sayAt": "01:14 / 01:26",
   "origin": "18 世纪末到 19 世纪，反映启蒙时期对古典主义的迷恋。",
   "usage": "正式印刷品；想要宏伟、永恒氛围的室内设计。",
   "tips": [
    "作者提到：随着苹果剧集《人生切割术》走红，这种风格的搜索量近期上涨"
   ],
   "n": 1
  },
  {
   "slug": "baroque",
   "en": "Baroque",
   "zh": "巴洛克",
   "group": "classical",
   "t": 117,
   "tc": "1:57",
   "desc": "用\"更多\"表达权力与激情：卷草曲线、金箔与厚重画框、斜向流动的构图、强烈的明暗对撞。装饰本身就是主角。",
   "traits": [
    "卷草曲线",
    "金箔·厚画框",
    "强明暗对撞",
    "斜向动势"
   ],
   "img": "img/baroque.jpg",
   "thumb": "img/thumbs/baroque.jpg",
   "accent": "#d0c176",
   "accentInk": "#6b633d",
   "tint": "#1d1c17",
   "tintLight": "#f1ecd2",
   "lum": 0.838,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=117",
   "videoName": "Baroque",
   "ref": {
    "img": "img/pd/baroque.jpg",
    "title": "Baroque ceiling frescoes (Ljubljana Cathedral).jpg",
    "artist": "Petar Milošević",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Baroque_ceiling_frescoes_(Ljubljana_Cathedral).jpg",
    "w": 1400,
    "h": 815,
    "bytes": 413429
   },
   "say": "想象一下戏剧性的细节、大量的装饰，对比让一切感觉奢华——就像你在一个经典剧院里。",
   "sayAt": "02:01 / 02:12",
   "origin": "17 世纪的欧洲蓬勃发展，延续到 18 世纪中叶，在那一时期主导了建筑和艺术。",
   "usage": "奢侈品牌视觉；需要更多优雅的编辑布局和包装。",
   "tips": [
    "别忽略那些看起来非常丰富的调色板，在这种风格里很重要"
   ],
   "n": 2
  },
  {
   "slug": "filigree",
   "en": "Filigree",
   "zh": "金细丝",
   "group": "classical",
   "t": 246,
   "tc": "4:06",
   "desc": "极细的金银丝工艺：细密卷曲的金属线、镂空结构、深色底上的描金线条。精致感来自\"线\"本身。",
   "traits": [
    "细金线",
    "镂空结构",
    "深底描金",
    "卷曲对称"
   ],
   "img": "img/filigree.jpg",
   "thumb": "img/thumbs/filigree.jpg",
   "accent": "#1aad31",
   "accentInk": "#1b6b27",
   "tint": "#171d18",
   "tintLight": "#d2f1d7",
   "lum": 0.197,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=246",
   "videoName": "FILIGREE",
   "ref": {
    "img": "img/pd/filigree.jpg",
    "title": "Cufflink Filigree.jpg",
    "artist": "Elfabso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Cufflink_Filigree.jpg",
    "w": 1400,
    "h": 781,
    "bytes": 228224
   },
   "say": "这种风格主要是关于那些复杂的蕾丝金属工艺，以及大理石和木工图案。",
   "sayAt": "04:07 / 04:31",
   "origin": "源于几个世纪前的金属工艺，特别是 17、18 世纪的欧洲。",
   "usage": "平面设计里它转化为奢华的卷曲、漩涡装饰，立刻传达出优雅；在字体设计里用得很多。适合婚礼请柬、高端奢侈品牌包装。",
   "tips": [
    "关键词就是“金银丝细工 / 卷曲漩涡装饰”"
   ],
   "n": 5
  },
  {
   "slug": "acanthus",
   "en": "Acanthus",
   "zh": "茛苕叶",
   "group": "classical",
   "t": 289,
   "tc": "4:49",
   "desc": "古典柱头与边框上的茛苕叶母题：叶片卷曲、重复铺排、带浮雕厚度。是西方装饰体系里最基础的一片叶子。",
   "traits": [
    "茛苕叶母题",
    "重复铺排",
    "浮雕厚度",
    "角饰边框"
   ],
   "img": "img/acanthus.jpg",
   "thumb": "img/thumbs/acanthus.jpg",
   "accent": "#e8c197",
   "accentInk": "#6b5c4b",
   "tint": "#1d1a17",
   "tintLight": "#f1e2d2",
   "lum": 0.789,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=289",
   "videoName": "ACANTHUS",
   "ref": {
    "img": "img/pd/acanthus.jpg",
    "title": "Feldkirchen Hauptplatz 2 Akanthusstuckfeld Madonnenmedaillon um 1700 02082018 6069.jpg",
    "artist": "Johann Jaritz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Feldkirchen_Hauptplatz_2_Akanthusstuckfeld_Madonnenmedaillon_um_1700_02082018_6069.jpg",
    "w": 1400,
    "h": 932,
    "bytes": 327016
   },
   "say": "这种风格突出了古希腊和罗马柱子中常见的叶状图案。",
   "sayAt": "04:52 / 05:09",
   "origin": "文艺复兴和新古典主义时期都见过这种风格的复兴。",
   "usage": "室内装饰、非常花哨的字体装饰，以及需要那种超级古典风格的优雅印刷布局和编辑设计。",
   "tips": [
    "作者说这是他最喜欢的风格之一"
   ],
   "n": 6
  },
  {
   "slug": "victorian",
   "en": "Victorian",
   "zh": "维多利亚",
   "group": "classical",
   "t": 724,
   "tc": "12:04",
   "desc": "19 世纪的繁复礼仪感：花体衬线、黑底金线、对称花框、密密麻麻的细节。第一眼就要\"贵\"。",
   "traits": [
    "花体衬线",
    "黑底金框",
    "对称构图",
    "繁复细节"
   ],
   "img": "img/victorian.jpg",
   "thumb": "img/thumbs/victorian.jpg",
   "accent": "#8c7744",
   "accentInk": "#6b5b34",
   "tint": "#1d1b17",
   "tintLight": "#f1e8d2",
   "lum": 0.192,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=724",
   "videoName": "VICTORIAN",
   "ref": {
    "img": "img/pd/victorian.jpg",
    "title": "Windsor Castle Upper Ward Quadrangle 2 - Nov 2006.jpg",
    "artist": "Diliff",
    "license": "CC BY 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/3.0",
    "page": "https://commons.wikimedia.org/wiki/File:Windsor_Castle_Upper_Ward_Quadrangle_2_-_Nov_2006.jpg",
    "w": 1400,
    "h": 738,
    "bytes": 270855
   },
   "say": "维多利亚设计风格以华丽的细节、丰富的色彩方案和花卉装饰为荣，它完全是关于过度的优雅和复杂的图案。",
   "sayAt": "12:04 / 12:19",
   "origin": "来自维多利亚女王的统治时期（1837–1901），这个时代极大影响了那个世纪的艺术、建筑和装饰。",
   "usage": "现代书法、主题活动邀请函、婚礼文具、复古品牌和包装。",
   "tips": [
    "蒸汽朋克美学也借用了这些复杂的字体形式"
   ],
   "n": 16
  },
  {
   "slug": "art-deco",
   "en": "Art Deco",
   "zh": "装饰艺术",
   "group": "classical",
   "t": 761,
   "tc": "12:41",
   "desc": "机器时代的几何奢华：放射线、阶梯状轮廓、严格对称的几何图案，配色常见金与墨绿、黑与奶油。",
   "traits": [
    "放射线",
    "阶梯几何",
    "严格对称",
    "金·墨绿"
   ],
   "img": "img/art-deco.jpg",
   "thumb": "img/thumbs/art-deco.jpg",
   "accent": "#1aad1a",
   "accentInk": "#1b6b1b",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.206,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=761",
   "videoName": "ART DECO",
   "ref": {
    "img": "img/pd/art-deco.jpg",
    "title": "2025.07.25 Private Collection Tatiana Markina Art Deco Jardiniere Horstensja Poland 1930s.jpg",
    "artist": "Tatiana Markina",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:2025.07.25_Private_Collection_Tatiana_Markina_Art_Deco_Jardiniere_Horstensja_Poland_1930s.jpg",
    "w": 1400,
    "h": 927,
    "bytes": 158937
   },
   "say": "它非常流畅、几何感强、非常迷人，采用对称的图案和金属装饰。",
   "sayAt": "12:50 / 12:56",
   "origin": "完全是关于现代奢华，主导了 1920 和 1930 年代，非常乐观地反映了那个战间时期。",
   "usage": "高端包装、精致活动、鸡尾酒吧、酒店，以及带有《了不起的盖茨比》风格的室内装饰。",
   "tips": [
    "你可能听说过这种风格，但总是忘记它叫什么——它就是这个词"
   ],
   "n": 17
  },
  {
   "slug": "art-nouveau",
   "en": "Art Nouveau",
   "zh": "新艺术",
   "group": "classical",
   "t": 794,
   "tc": "13:14",
   "desc": "从植物与女性身体曲线里长出来的线条：连绵的鞭形曲线、有机边框把主体围起来、穆夏式的装饰人物。",
   "traits": [
    "鞭形曲线",
    "有机边框",
    "穆夏式人物",
    "手绘轮廓"
   ],
   "img": "img/art-nouveau.jpg",
   "thumb": "img/thumbs/art-nouveau.jpg",
   "accent": "#967c4d",
   "accentInk": "#6b5937",
   "tint": "#1d1b17",
   "tintLight": "#f1e6d2",
   "lum": 0.791,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=794",
   "videoName": "ART NOUVEAU",
   "ref": {
    "img": "img/pd/art-nouveau.jpg",
    "title": "Art Nouveau Riga 46.jpg",
    "artist": "Scotch Mist",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Art_Nouveau_Riga_46.jpg",
    "w": 1400,
    "h": 931,
    "bytes": 270225
   },
   "say": "它采用流畅的线条、有机的形状、花卉图案和优雅的圆润字体，深受自然启发，通常把插图和字体无缝结合。",
   "sayAt": "13:18 / 13:30",
   "origin": "19 世纪末由阿尔丰斯·穆夏（Alphonse Mucha）等艺术家发起，部分是对工业大规模生产的回应。",
   "usage": "海报设计、书籍封面，以及那些想要更具手工感、浪漫和有机感觉的品牌。",
   "tips": [
    "搜索“阿尔丰斯·穆夏”的名字，能找到大量同类风格"
   ],
   "n": 18
  },
  {
   "slug": "gothic",
   "en": "Gothic",
   "zh": "哥特",
   "group": "classical",
   "t": 1318,
   "tc": "21:58",
   "desc": "阴暗、尖拱与神秘：尖拱与玫瑰窗母题、深色配血红、黑体与花体混排，适合表达超自然与不安。",
   "traits": [
    "尖拱母题",
    "深色·血红",
    "黑体+花体",
    "超自然气"
   ],
   "img": "img/gothic.jpg",
   "thumb": "img/thumbs/gothic.jpg",
   "accent": "#1aad1a",
   "accentInk": "#1b6b1b",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.055,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1318",
   "videoName": "GOTHIC",
   "ref": {
    "img": "img/pd/gothic.jpg",
    "title": "Iglesia de San Miguel, Jerez de la Frontera, España, 2015-12-07, DD 105-107 HDR.JPG",
    "artist": "Diego Delso",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Iglesia_de_San_Miguel,_Jerez_de_la_Frontera,_Espa%C3%B1a,_2015-12-07,_DD_105-107_HDR.JPG",
    "w": 1400,
    "h": 917,
    "bytes": 393405
   },
   "say": "想象一下尖拱、复杂的雕刻和黑暗的雕塑；哥特风格非常戏剧化，可以偏向阴森，也可以偏向宏伟，取决于你的需求。",
   "sayAt": "22:01 / 22:33",
   "origin": "哥特式建筑在 12 世纪的欧洲兴起，并影响了后来的各种复兴。",
   "usage": "从边缘乐队商品标志、复古品牌到时尚，范围相当广泛。",
   "tips": [
    "它非常戏剧化，可以偏向阴森，也可以偏向宏伟，取决于你的需求"
   ],
   "n": 32
  },
  {
   "slug": "steampunk",
   "en": "Steampunk",
   "zh": "蒸汽朋克",
   "group": "classical",
   "t": 1455,
   "tc": "24:15",
   "desc": "维多利亚加蒸汽机械的幻想：黄铜齿轮、皮革与铜绿、繁复的机械结构、旧式衬线体做标题。",
   "traits": [
    "黄铜齿轮",
    "皮革·铜绿",
    "机械繁复",
    "维多利亚底"
   ],
   "img": "img/steampunk.jpg",
   "thumb": "img/thumbs/steampunk.jpg",
   "accent": "#ad8a71",
   "accentInk": "#6b5546",
   "tint": "#1d1a17",
   "tintLight": "#f1dfd2",
   "lum": 0.604,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1455",
   "videoName": "STEAMPUNK",
   "ref": {
    "img": "img/pd/steampunk.jpg",
    "title": "Steampunk-Traktor Frank John-Lorenz 20191129 074146.jpg",
    "artist": "Frank John-Lorenz selbst erschaffen von Frank John-Lorenz",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "page": "https://commons.wikimedia.org/wiki/File:Steampunk-Traktor_Frank_John-Lorenz_20191129_074146.jpg",
    "w": 1400,
    "h": 680,
    "bytes": 155584
   },
   "say": "蒸汽朋克融合了维多利亚时代的美学与机械蒸汽动力技术，以一种复古未来主义的方式——虽然一切看起来都像来自过去的时代，但机械发明甚至比我们今天的技术还要先进。",
   "sayAt": "24:24 / 24:36",
   "origin": "起源于 1980 年代的文学子类型，然后发展成为一个更广泛的流行文化现象。",
   "usage": "书籍封面、奇幻品牌视觉、把历史与科学结合的商品，以及适合这种美学的视频游戏图形。",
   "tips": [
    "视觉关键词：齿轮、大量的齿轮、大量的黄铜装置"
   ],
   "n": 35
  },
  {
   "slug": "tenebrism",
   "en": "Tenebrism",
   "zh": "暗色调主义",
   "group": "painting",
   "t": 1277,
   "tc": "21:17",
   "desc": "把光压成一把刀：背景近乎全黑，只用单侧硬光雕出主体，极端明暗比带来舞台般的戏剧感。",
   "traits": [
    "近黑背景",
    "单侧硬光",
    "极端明暗比",
    "戏剧舞台感"
   ],
   "img": "img/tenebrism.jpg",
   "thumb": "img/thumbs/tenebrism.jpg",
   "accent": "#20ad9e",
   "accentInk": "#1b6b62",
   "tint": "#171d1d",
   "tintLight": "#d2f1ed",
   "lum": 0.179,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1277",
   "videoName": "Tenebrism",
   "ref": {
    "img": "img/pd/tenebrism.jpg",
    "title": "The Nightwatch by Rembrandt - Rijksmuseum.jpg",
    "artist": "Rembrandt",
    "license": "Public domain",
    "licenseUrl": "",
    "page": "https://commons.wikimedia.org/wiki/File:The_Nightwatch_by_Rembrandt_-_Rijksmuseum.jpg",
    "w": 1400,
    "h": 1139,
    "bytes": 275031
   },
   "say": "这种风格依赖于极端的光影对比，创造出高戏剧性的聚光灯效果：把观众的注意力吸引到明亮的区域，背景则是深沉的阴影。",
   "sayAt": "21:24 / 21:39",
   "origin": "这种技术起源于 17 世纪的巴洛克绘画，由卡拉瓦乔等艺术家推广。",
   "usage": "氛围海报、活动传单、编辑排版、网页设计，以及需要强烈视觉吸引力的包装设计。",
   "tips": [
    "它更像是一个艺术术语；通常非常强烈、非常阴郁"
   ],
   "n": 31
  },
  {
   "slug": "pointilism",
   "en": "Pointilism",
   "zh": "点彩",
   "group": "painting",
   "t": 1368,
   "tc": "22:48",
   "desc": "用密密麻麻的小色点堆出画面，靠眼睛把颜色混起来；同时天然带着网点/半调的印刷质感。",
   "traits": [
    "细密色点",
    "光学混色",
    "网点半调",
    "朦胧边界"
   ],
   "img": "img/pointilism.jpg",
   "thumb": "img/thumbs/pointilism.jpg",
   "accent": "#90ae71",
   "accentInk": "#5b6b4b",
   "tint": "#1a1d17",
   "tintLight": "#e1f1d2",
   "lum": 0.873,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1368",
   "videoName": "POINTILLISM",
   "ref": {
    "img": "img/pd/pointilism.jpg",
    "title": "Paul Gosselin - On the beach of Oostende - Impressionism,Pointillism 1987.jpg",
    "artist": "Paul Gosselin",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "page": "https://commons.wikimedia.org/wiki/File:Paul_Gosselin_-_On_the_beach_of_Oostende_-_Impressionism,Pointillism_1987.jpg",
    "w": 1400,
    "h": 988,
    "bytes": 508085
   },
   "say": "点彩画法通过数千个小点排列成图案：从远处看，眼睛会把它们融合成一个连贯的图像；近距离看，它有一种独特的点状外观。",
   "sayAt": "22:48 / 22:59",
   "origin": "这种技术在 19 世纪末发展起来。",
   "usage": "编辑插图、品牌设计，以及需要更具艺术感的包装设计。",
   "tips": [
    "可以搜索“点彩艺术”找类似结果",
    "作者的做法：起初用微米笔手绘，很快就累了，改用电子点画笔完成"
   ],
   "n": 33
  },
  {
   "slug": "surrealism",
   "en": "Surrealism",
   "zh": "超现实主义",
   "group": "painting",
   "t": 1601,
   "tc": "26:41",
   "desc": "把不相干的东西放进同一个梦：尺度错置、物体拼接、日常之物被陌生化。逻辑服从梦境。",
   "traits": [
    "尺度错置",
    "物体拼接",
    "梦境逻辑",
    "日常陌生化"
   ],
   "img": "img/surrealism.jpg",
   "thumb": "img/thumbs/surrealism.jpg",
   "accent": "#57ad57",
   "accentInk": "#366b36",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.323,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1601",
   "videoName": "SURREALISM DESIGN",
   "ref": {
    "img": "img/pd/surrealism.jpg",
    "title": "Surrealism in photography 06.jpg",
    "artist": "Mostafameraji",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "page": "https://commons.wikimedia.org/wiki/File:Surrealism_in_photography_06.jpg",
    "w": 1400,
    "h": 933,
    "bytes": 72789
   },
   "say": "超现实主义风格把逻辑抛在一边，它将日常物品和超梦幻的物品结合在一起，触及你的潜意识：使用不相关的图像，激发好奇心，并挑战现实。",
   "sayAt": "26:43 / 26:58",
   "origin": "它起源于 1920 年代，并持续影响着我们的设计、电影和广告。",
   "usage": "专辑封面、编辑插图，旨在引发思考。",
   "tips": [
    "关键是把不相关的图像并置"
   ],
   "n": 38
  },
  {
   "slug": "mixed-media",
   "en": "Mixed Media",
   "zh": "混合媒介",
   "group": "painting",
   "t": 1417,
   "tc": "23:37",
   "desc": "把不同材料放进同一张画面：撕纸边缘、摄影与手绘叠加、层层拼贴，质感冲突本身就是内容。",
   "traits": [
    "撕纸边缘",
    "摄影+手绘",
    "层叠拼贴",
    "材质对比"
   ],
   "img": "img/mixed-media.jpg",
   "thumb": "img/thumbs/mixed-media.jpg",
   "accent": "#ad8c6f",
   "accentInk": "#6b5745",
   "tint": "#1d1a17",
   "tintLight": "#f1e0d2",
   "lum": 0.42,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1417",
   "videoName": "MIXED MEDIA",
   "say": "混合媒体风格是关于结合不同的媒介——混合绘画、摄影、拼贴，把它们统一成一个构图，通常用分层和意想不到的位置创造非常折衷的视觉效果。",
   "sayAt": "23:37 / 23:53",
   "origin": "艺术家们已经使用混合媒体很长时间，但在 20 世纪末，设计师开始把这种风格引入数字时代。",
   "usage": "杂志排版、专辑封面、广告。",
   "tips": [
    "关键手法：分层 + 意想不到的摆放位置"
   ],
   "n": 34
  },
  {
   "slug": "anthropomorphic",
   "en": "Anthropomorphic",
   "zh": "拟人化",
   "group": "painting",
   "t": 322,
   "tc": "5:22",
   "desc": "给动物、器物、自然物装上人的形体与表情：拟人角色、动物穿人类衣装、夸张情绪，天然适合叙事插画。",
   "traits": [
    "拟人角色",
    "人形动物",
    "夸张表情",
    "叙事插画"
   ],
   "img": "img/anthropomorphic.jpg",
   "thumb": "img/thumbs/anthropomorphic.jpg",
   "accent": "#ac70a3",
   "accentInk": "#6b4b66",
   "tint": "#1d171c",
   "tintLight": "#f1d2ec",
   "lum": 0.726,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=322",
   "videoName": "ANTHROPOMORPHIC",
   "ref": {
    "img": "img/pd/anthropomorphic.jpg",
    "title": "Navagraha (anthropomorphic forms of astronomical bodies), Bihar, India, 10th century AD, schist - San Diego Museum of Art - DSC06389.JPG",
    "artist": "Daderot",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "page": "https://commons.wikimedia.org/wiki/File:Navagraha_(anthropomorphic_forms_of_astronomical_bodies),_Bihar,_India,_10th_century_AD,_schist_-_San_Diego_Museum_of_Art_-_DSC06389.JPG",
    "w": 1400,
    "h": 812,
    "bytes": 299828
   },
   "say": "这是指非人类物体（比如动物）具有人类特征；这种设计风格非常 whimsical（异想天开），能迅速把简单的想法转化为有亲和力的角色。",
   "sayAt": "05:24 / 06:02",
   "origin": "可以追溯到古代神话，但商业繁荣发生在 20 世纪，随着卡通和品牌吉祥物的兴起。",
   "usage": "儿童书籍、有趣的品牌活动，或复古产品包装。",
   "tips": [
    "搜“拟人化”时谷歌可能会给你推荐“动物标本制作”，完全不是一回事"
   ],
   "n": 7
  },
  {
   "slug": "conceptual-sketch",
   "en": "Conceptual Sketch",
   "zh": "概念草图",
   "group": "painting",
   "t": 432,
   "tc": "7:12",
   "desc": "像草稿本上撕下来的一页：单色线稿、指示箭头、手写批注、故意留着的\"没画完\"。",
   "traits": [
    "单色线稿",
    "箭头+批注",
    "手绘不规整",
    "构思中"
   ],
   "img": "img/conceptual-sketch.jpg",
   "thumb": "img/thumbs/conceptual-sketch.jpg",
   "accent": "#b0e696",
   "accentInk": "#566b4b",
   "tint": "#191d17",
   "tintLight": "#dcf1d2",
   "lum": 0.908,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=432",
   "videoName": "CONCEPTUAL SKETCH",
   "ref": {
    "img": "img/pd/conceptual-sketch.jpg",
    "title": "1915 - Allentown High School Conceptual Drawing Allentown PA.jpg",
    "artist": "Unknown authorUnknown author",
    "license": "Public domain",
    "licenseUrl": "",
    "page": "https://commons.wikimedia.org/wiki/File:1915_-_Allentown_High_School_Conceptual_Drawing_Allentown_PA.jpg",
    "w": 1400,
    "h": 789,
    "bytes": 153717
   },
   "say": "这种风格的主要特点是自发的、孩子般的、甚至有些天真的绘画，非常自由形式。",
   "sayAt": "07:21 / 07:38",
   "origin": "素描本身已经存在了很长时间，但这种涂鸦艺术在 2000 年代之后真正流行起来。",
   "usage": "品牌、创意机构、面向年轻人的产品或品牌，以及想展示更多趣味或未打磨能量的编辑设计。",
   "tips": [
    "也可以搜作“涂鸦艺术”（doodle art），两者效果类似",
    "作者的做法：在笔记本上随手画，扫描后矢量化，就能快速做成设计元素"
   ],
   "n": 9
  },
  {
   "slug": "pop-art",
   "en": "Pop Art",
   "zh": "波普艺术",
   "group": "painting",
   "t": 1175,
   "tc": "19:35",
   "desc": "把大众图像直接搬进艺术：粗描边、网点、原色平涂、漫画式重复排列，明快且大声。",
   "traits": [
    "粗描边",
    "网点",
    "原色平涂",
    "漫画式重复"
   ],
   "img": "img/pop-art.jpg",
   "thumb": "img/thumbs/pop-art.jpg",
   "accent": "#2a54ad",
   "accentInk": "#1b346b",
   "tint": "#17191d",
   "tintLight": "#d2dcf1",
   "lum": 0.444,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1175",
   "videoName": "POP ART",
   "ref": {
    "img": "img/pd/pop-art.jpg",
    "title": "Pintura em Pop Art para Elephant Parade.jpg",
    "artist": "Lobo Pop Art",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "page": "https://commons.wikimedia.org/wiki/File:Pintura_em_Pop_Art_para_Elephant_Parade.jpg",
    "w": 1280,
    "h": 853,
    "bytes": 143977
   },
   "say": "它将日常物品、漫画图像和著名图标结合在一起，然后用大胆的色彩和重复来制造强烈的视觉冲击。",
   "sayAt": "19:40 / 19:57",
   "origin": "起源于 1950 到 1960 年代，由安迪·沃霍尔和罗伊·利希滕斯坦等艺术家推广。",
   "usage": "品牌、服装设计、网页设计、编辑封面、包装设计。",
   "tips": [
    "它像是对消费主义和名人文化的结合评论，通常非常有趣、非常引人注目"
   ],
   "n": 28
  },
  {
   "slug": "kitsch",
   "en": "Kitsch",
   "zh": "媚俗",
   "group": "painting",
   "t": 887,
   "tc": "14:47",
   "desc": "明知俗气而为之：高饱和、廉价塑料感、怀旧符号层层堆叠，甜得发腻——但要的就是这个效果。",
   "traits": [
    "高饱和",
    "廉价塑料感",
    "怀旧符号",
    "甜腻反讽"
   ],
   "img": "img/kitsch.jpg",
   "thumb": "img/thumbs/kitsch.jpg",
   "accent": "#6e8fa9",
   "accentInk": "#4b5d6b",
   "tint": "#171a1d",
   "tintLight": "#d2e3f1",
   "lum": 0.769,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=887",
   "videoName": "KITSCH",
   "ref": {
    "img": "img/pd/kitsch.jpg",
    "title": "Kitsch Buddhas (8569927671).jpg",
    "artist": "Andrew Moore from Johannesburg, South Africa",
    "license": "CC BY-SA 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/2.0",
    "page": "https://commons.wikimedia.org/wiki/File:Kitsch_Buddhas_(8569927671).jpg",
    "w": 1400,
    "h": 990,
    "bytes": 383176
   },
   "say": "这种风格把俗气变成了一种艺术形式——很多明亮的色彩、夸张的图像和俏皮的流行文化参考。",
   "sayAt": "14:52 / 15:06",
   "origin": "Kitsch 的概念可以追溯到 19 世纪，但在 20 世纪中叶的波普艺术中得到了显著的复兴。",
   "usage": "讽刺品牌、新奇产品、贴纸，以及那些想要过度夸张的营销活动。",
   "tips": [
    "它非常有趣、非常讽刺、非常怀旧，带有很多复古图形元素"
   ],
   "n": 20
  },
  {
   "slug": "bauhaus",
   "en": "Bauhaus",
   "zh": "包豪斯",
   "group": "modern",
   "t": 992,
   "tc": "16:32",
   "desc": "形式追随功能：红黄蓝加黑、只用基本几何形、无衬线体的网格排版、把装饰全部删掉。",
   "traits": [
    "红黄蓝+黑",
    "基本几何",
    "无衬线网格",
    "彻底去装饰"
   ],
   "img": "img/bauhaus.jpg",
   "thumb": "img/thumbs/bauhaus.jpg",
   "accent": "#dd2b60",
   "accentInk": "#6b1b33",
   "tint": "#1d1719",
   "tintLight": "#f1d2db",
   "lum": 0.576,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=992",
   "videoName": "BAUHAUS",
   "ref": {
    "img": "img/pd/bauhaus.jpg",
    "title": "Außenansichten des Bauhaus-Gebäudes in Dessau 06.jpg",
    "artist": "JensKunstfreund",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Au%C3%9Fenansichten_des_Bauhaus-Geb%C3%A4udes_in_Dessau_06.jpg",
    "w": 1400,
    "h": 729,
    "bytes": 225304
   },
   "say": "包豪斯风格将设计简化为功能性必需品，使用大胆的几何形状、原色和极少的装饰，完全是关于形式服从功能和清晰性。",
   "sayAt": "16:32 / 16:45",
   "origin": "起源于 1919 到 1930 年间的德国艺术学校，为全球的现代主义设计奠定了基础。",
   "usage": "品牌标识设计、编辑和网页设计的网格布局，以及需要更流畅几何外观的产品设计。",
   "tips": [
    "它也影响了前面讲过的 Japandi"
   ],
   "n": 23
  },
  {
   "slug": "brutalism",
   "en": "Brutalism",
   "zh": "粗野主义",
   "group": "modern",
   "t": 1028,
   "tc": "17:08",
   "desc": "把材料与结构裸露出来：裸露混凝土或裸排版、粗黑边框、不加修饰的默认字体，反精致。",
   "traits": [
    "裸露结构",
    "粗黑边框",
    "默认字体",
    "反精致"
   ],
   "img": "img/brutalism.jpg",
   "thumb": "img/thumbs/brutalism.jpg",
   "accent": "#ad3a7e",
   "accentInk": "#6b244e",
   "tint": "#1d171b",
   "tintLight": "#f1d2e4",
   "lum": 0.487,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1028",
   "videoName": "BRUTALISM",
   "ref": {
    "img": "img/pd/brutalism.jpg",
    "title": "Brutalist architecture of UMass Dartmouth.jpg",
    "artist": "Kenneth C. Zirkel",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Brutalist_architecture_of_UMass_Dartmouth.jpg",
    "w": 1400,
    "h": 599,
    "bytes": 176022
   },
   "say": "在平面设计中，粗野主义把抛光的极简主义抛在一边，它更喜欢更鲜明的布局、大胆的单色调色板，以及未经过多修饰的字体；它故意保持原始感，并挑战更传统的网格和美学。",
   "sayAt": "17:08 / 17:27",
   "origin": "受 20 世纪中叶建筑粗野主义的启发。",
   "usage": "街头服饰、实验性品牌、编辑布局。",
   "tips": [
    "可以搜“极繁主义”或“粗野主义”来找同类设计"
   ],
   "n": 24
  },
  {
   "slug": "mid-century",
   "en": "Mid Century",
   "zh": "世纪中叶现代",
   "group": "modern",
   "t": 1678,
   "tc": "27:58",
   "desc": "战后乐观的现代主义：暖木色与芥末黄、抽象有机几何、细长的无衬线体，带一点印刷颗粒。",
   "traits": [
    "暖木·芥末黄",
    "有机几何",
    "细长无衬线",
    "印刷颗粒"
   ],
   "img": "img/mid-century.jpg",
   "thumb": "img/thumbs/mid-century.jpg",
   "accent": "#98d1eb",
   "accentInk": "#4b616b",
   "tint": "#171b1d",
   "tintLight": "#d2e7f1",
   "lum": 0.838,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1678",
   "videoName": "MID CENTURY",
   "say": "世纪中叶风格采用简洁的线条、现代乐观主义和略微柔和的色彩；流畅的轮廓、有机曲线和对太空时代创新的致敬，是这种设计风格的主要部分。",
   "sayAt": "28:00 / 28:12",
   "origin": "大致从 1945 到 1970 年，这个时代在二战后见证了现代设计的繁荣。",
   "usage": "家具品牌、复古海报布局，以及许多庆祝经典现代主义的家居装饰。",
   "tips": [
    "作者的建议：多想想那个时代的家具"
   ],
   "n": 40
  },
  {
   "slug": "utilitarian",
   "en": "Utilitarian",
   "zh": "功利主义",
   "group": "modern",
   "t": 1636,
   "tc": "27:16",
   "desc": "以好用为唯一准绳：没有装饰、字大到不容忽视、黑白高对比、信息永远排在美观前面。",
   "traits": [
    "零装饰",
    "直白大字",
    "黑白高对比",
    "信息优先"
   ],
   "img": "img/utilitarian.jpg",
   "thumb": "img/thumbs/utilitarian.jpg",
   "accent": "#98eb98",
   "accentInk": "#4b6b4b",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.814,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1636",
   "videoName": "UTILITARIANISM",
   "say": "它将设计简化为基本要素，专注于实用性和功能性，而不是装饰性；它通常非常简洁、极简，让信息一目了然——因为大多数时候它只是大量的字体排列成网格。",
   "sayAt": "27:20 / 27:36",
   "origin": "这种思维方式与 20 世纪中叶的现代主义原则一起出现，并在极简主义设计运动中复兴。",
   "usage": "标志、工业界面、服装标签、包装设计，以及任何需要在狭小空间中传达大量信息的地方。",
   "tips": [
    "作者说这可能是他现在最喜欢的风格之一",
    "理解它的简单方式：想想集装箱"
   ],
   "n": 39
  },
  {
   "slug": "luxury-typography",
   "en": "Luxury Typography",
   "zh": "奢华字体",
   "group": "modern",
   "t": 492,
   "tc": "8:12",
   "desc": "让排版本身显得昂贵：极高对比的现代衬线体、宽字距、大片留白、金色字压在深色或实景底图上。",
   "traits": [
    "高对比衬线",
    "宽字距",
    "大片留白",
    "金字压图"
   ],
   "img": "img/luxury-typography.jpg",
   "thumb": "img/thumbs/luxury-typography.jpg",
   "accent": "#ad544c",
   "accentInk": "#6b342f",
   "tint": "#1d1717",
   "tintLight": "#f1d4d2",
   "lum": 0.325,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=492",
   "videoName": "LUXURY",
   "ref": {
    "img": "img/pd/luxury-typography.jpg",
    "title": "Poster XXXIII. Výstava SPU Mánes 1910.jpg",
    "artist": "František Kysela",
    "license": "Public domain",
    "licenseUrl": "",
    "page": "https://commons.wikimedia.org/wiki/File:Poster_XXXIII._V%C3%BDstava_SPU_M%C3%A1nes_1910.jpg",
    "w": 1200,
    "h": 893,
    "bytes": 160675
   },
   "say": "这种方法主要是关于超级精致的、漂亮的自定义字体，带有奢华或非常复杂的连字。",
   "sayAt": "08:15 / 08:23",
   "origin": "20 世纪的高端时尚品牌让这种风格广为人知，它植根于古老的书法传统。",
   "usage": "高端包装、奢侈街头服饰品牌、高档活动和邀请函、杂志封面。",
   "tips": [
    "在 Pinterest 输入“奢华字体设计”，会出来很多参考"
   ],
   "n": 10
  },
  {
   "slug": "3x3-grid",
   "en": "3x3 Grid",
   "zh": "九宫格",
   "group": "modern",
   "t": 922,
   "tc": "15:22",
   "desc": "把内容收进 3×3 的九格：规则分格、中心对称、图标配短标签、每个格子分量相等。",
   "traits": [
    "3×3 分格",
    "强对齐",
    "图标+短标签",
    "秩序感"
   ],
   "img": "img/3x3-grid.jpg",
   "thumb": "img/thumbs/3x3-grid.jpg",
   "accent": "#8cd7d7",
   "accentInk": "#4b6b6b",
   "tint": "#171d1d",
   "tintLight": "#d2f1f1",
   "lum": 0.814,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=922",
   "videoName": "3X3 GRID DESIGN",
   "ref": {
    "img": "img/pd/3x3-grid.jpg",
    "title": "Karl Gerstner Capital layout grid.png",
    "artist": "Manuel Schmalstieg",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Karl_Gerstner_Capital_layout_grid.png",
    "w": 1400,
    "h": 819,
    "bytes": 64482
   },
   "say": "3×3 网格设计将视觉元素组织成九个均匀分布的方框，网格系统是这种风格的基础。",
   "sayAt": "15:26 / 15:45",
   "origin": "3×3 布局在 2014 到 2015 年，随着社交媒体与情绪板的结合而变得特别流行。",
   "usage": "Instagram 动态、作品集，以及很多服装和精品设计。",
   "tips": [
    "这也是作者自创的词——他看到很多这种设计，却没有术语能帮你搜到它",
    "非常简单易懂，关键就是网格"
   ],
   "n": 21
  },
  {
   "slug": "bento-box",
   "en": "Bento Box",
   "zh": "便当盒",
   "group": "modern",
   "t": 1216,
   "tc": "20:16",
   "desc": "用大小不一的圆角格子组织界面：层级明确、一屏之内讲完所有事，像便当盒的分格。",
   "traits": [
    "圆角格子",
    "明确层级",
    "一屏总览",
    "模块化"
   ],
   "img": "img/bento-box.jpg",
   "thumb": "img/thumbs/bento-box.jpg",
   "accent": "#1aad1a",
   "accentInk": "#1b6b1b",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.496,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1216",
   "videoName": "BENTO GRID",
   "ref": {
    "img": "img/pd/bento-box.jpg",
    "title": "Handmade bento 03.jpg",
    "artist": "Novoklimov",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Handmade_bento_03.jpg",
    "w": 1400,
    "h": 1050,
    "bytes": 228770
   },
   "say": "便当网格是一种整洁有序的布局风格，灵感来自分区的日本便当盒——每个部分都有自己专用的空间，非常整洁和模块化。",
   "sayAt": "20:16 / 20:29",
   "origin": "2012 年左右在 UI/UX 和网页设计中获得了很大的关注，得益于对极简、功能性和易读布局的推动。",
   "usage": "仪表板、作品集，以及许多苹果产品风格的品牌网站。",
   "tips": [
    "它适合任何需要精致、结构化呈现的项目"
   ],
   "n": 29
  },
  {
   "slug": "mystical-western",
   "en": "Mystical Western",
   "zh": "神秘西部",
   "group": "modern",
   "t": 839,
   "tc": "13:59",
   "desc": "美国西部加神秘学：沙色与晚霞渐变、太阳与塔罗图腾、老式票据/木刻字体、粗描边的插画。",
   "traits": [
    "沙色·晚霞",
    "图腾与塔罗",
    "票据木刻字",
    "粗描边插画"
   ],
   "img": "img/mystical-western.jpg",
   "thumb": "img/thumbs/mystical-western.jpg",
   "accent": "#ad8d71",
   "accentInk": "#6b5847",
   "tint": "#1d1a17",
   "tintLight": "#f1e0d2",
   "lum": 0.752,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=839",
   "videoName": "MYSTICAL WESTERN",
   "say": "这种风格结合了经典的牛仔氛围和一丝宇宙灵性——想象沙漠景观、月光和天体符号。",
   "sayAt": "14:15 / 14:25",
   "origin": "西部艺术可以追溯到 19 世纪，但神秘元素是在现代波西米亚圈中兴起（又是 2010 年代）。",
   "usage": "音乐节海报、独立品牌，以及那些想捕捉更梦幻美学的品牌。",
   "tips": [
    "这是作者自创的关键词：可以分别搜“神秘”和“西部”，或搜“塔罗牌”"
   ],
   "n": 19
  },
  {
   "slug": "pixel-art",
   "en": "Pixel Art",
   "zh": "像素艺术",
   "group": "digital",
   "t": 387,
   "tc": "6:27",
   "desc": "以看得见的方块为最小单位作画：低分辨率网格、有限调色板、用抖动（dithering）来过渡颜色。",
   "traits": [
    "像素网格",
    "有限调色板",
    "抖动过渡",
    "复古游戏感"
   ],
   "img": "img/pixel-art.jpg",
   "thumb": "img/thumbs/pixel-art.jpg",
   "accent": "#1aad1a",
   "accentInk": "#1b6b1b",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.033,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=387",
   "videoName": "PIXEL ART",
   "ref": {
    "img": "img/pd/pixel-art.jpg",
    "title": "Pixel art opened envelope on table.png",
    "artist": "AnubiArts",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Pixel_art_opened_envelope_on_table.png",
    "w": 1344,
    "h": 1088,
    "bytes": 11472
   },
   "say": "像素艺术通常被称为 8 位或位图艺术——来自早期计算机或视频游戏的块状低分辨率图形。",
   "sayAt": "06:29 / 06:46",
   "origin": "有人说它在 70 到 80 年代达到顶峰，2010 年代的独立游戏里又有所回归，现在又开始流行。",
   "usage": "复古风格的营销、独立游戏设计，或需要那种 80 年代像素风格的图形。",
   "tips": [
    "关键特征：小方块的颜色、有限的调色板，非常复古怀旧"
   ],
   "n": 8
  },
  {
   "slug": "y2k",
   "en": "Y2K",
   "zh": "千禧年",
   "group": "digital",
   "t": 959,
   "tc": "15:59",
   "desc": "2000 年前后的科技乐观：亮蓝与银、气泡与半透明外壳、金属渐变、圆润的科技字体。",
   "traits": [
    "亮蓝·银",
    "气泡透明感",
    "金属渐变",
    "圆润科技字"
   ],
   "img": "img/y2k.jpg",
   "thumb": "img/thumbs/y2k.jpg",
   "accent": "#2a60c1",
   "accentInk": "#1b386b",
   "tint": "#17191d",
   "tintLight": "#d2ddf1",
   "lum": 0.597,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=959",
   "videoName": "Y2K",
   "say": "Y2K 捕捉了千禧年之交的科技乐观主义和未来主义外观。",
   "sayAt": "16:07 / 16:14",
   "origin": "在 1999 到 2000 年左右兴起，现在正享受自己的复兴——大约从 2020 年开始。",
   "usage": "时尚编辑、数字拼贴、街头服饰品牌活动，那些希望重新融入怀旧文化的品牌。",
   "tips": [
    "关键元素：粗糙的纹理、霓虹灯、泡泡或未来主义字体"
   ],
   "n": 22
  },
  {
   "slug": "cybercore",
   "en": "Cybercore",
   "zh": "赛博核心",
   "group": "digital",
   "t": 1068,
   "tc": "17:48",
   "desc": "数字化、故障与监控感：荧光绿、扫描线与画面错位、界面/HUD 叠加在人像上，冷硬且不安。",
   "traits": [
    "荧光绿",
    "扫描线·故障",
    "HUD 叠加",
    "冷硬不安"
   ],
   "img": "img/cybercore.jpg",
   "thumb": "img/thumbs/cybercore.jpg",
   "accent": "#679863",
   "accentInk": "#4c6b49",
   "tint": "#171d17",
   "tintLight": "#d4f1d2",
   "lum": 0.363,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1068",
   "videoName": "CYBERCORE",
   "ref": {
    "img": "img/pd/cybercore.jpg",
    "title": "Cyberpunk City.jpg",
    "artist": "Missingnokz",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Cyberpunk_City.jpg",
    "w": 1400,
    "h": 766,
    "bytes": 143256
   },
   "say": "它完全是关于霓虹灯照明的视觉效果，带有类似电路板的图案，让人感觉更像生活在一个高科技世界里。",
   "sayAt": "17:53 / 18:06",
   "origin": "植根于赛博朋克的概念，随着 21 世纪的互联网繁荣再次流行；2024 年这个关键词完全复苏。",
   "usage": "游戏品牌、海报设计、营销活动、愿景板，以及任何需要更具边缘感的数字品牌。",
   "tips": [
    "视觉关键词：金属质感、硬阴影、弹出窗口、数字速度感"
   ],
   "n": 25
  },
  {
   "slug": "synthwave",
   "en": "Synthwave",
   "zh": "合成波",
   "group": "digital",
   "t": 1107,
   "tc": "18:27",
   "desc": "对 80 年代电子乐的怀旧：紫粉霓虹、网格地平线、镀铬反光字、夕阳渐变，一切都在发光。",
   "traits": [
    "紫粉霓虹",
    "网格地平线",
    "镀铬字",
    "夕阳渐变"
   ],
   "img": "img/synthwave.jpg",
   "thumb": "img/thumbs/synthwave.jpg",
   "accent": "#57ad57",
   "accentInk": "#366b36",
   "tint": "#171d17",
   "tintLight": "#d2f1d2",
   "lum": 0.297,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1107",
   "videoName": "SYNTHWAVE",
   "ref": {
    "img": "img/pd/synthwave.jpg",
    "title": "Perturbator - Rock am Ring 2017-AL6980.jpg",
    "artist": "Andreas Lawen, Fotandi",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Perturbator_-_Rock_am_Ring_2017-AL6980.jpg",
    "w": 1400,
    "h": 794,
    "bytes": 107228
   },
   "say": "合成波风格借鉴了 80 年代的怀旧情怀，带有霓虹灯网格、棕榈树（不知道为什么），以及那些戏剧性的日落渐变。",
   "sayAt": "18:32 / 18:42",
   "origin": "这是一种复古未来主义风格，深受电子音乐和老式 80 年代街机美学的影响；2000 年代末 80 年代合成音乐的复兴让它重新流行。",
   "usage": "专辑艺术、品牌推广、营销活动，任何需要霓虹灯效果的设计。",
   "tips": [
    "作者说设计师大约在 2008 到 2009 年广泛使用这种风格"
   ],
   "n": 26
  },
  {
   "slug": "vaporwave",
   "en": "Vaporwave",
   "zh": "蒸汽波",
   "group": "digital",
   "t": 1140,
   "tc": "19:00",
   "desc": "对消费主义与早期互联网的暧昧怀旧：粉紫渐层、古典雕像、旧系统窗口、日文乱入，拼贴成失落的商场。",
   "traits": [
    "粉紫渐层",
    "古典雕像",
    "旧界面元素",
    "日文拼贴"
   ],
   "img": "img/vaporwave.jpg",
   "thumb": "img/thumbs/vaporwave.jpg",
   "accent": "#8b5db7",
   "accentInk": "#51366b",
   "tint": "#1a171d",
   "tintLight": "#e2d2f1",
   "lum": 0.733,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1140",
   "videoName": "VAPORWAVE",
   "ref": {
    "img": "img/pd/vaporwave.jpg",
    "title": "Vaporwave WP3 Print.jpg",
    "artist": "Mike Grauer Jr",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "page": "https://commons.wikimedia.org/wiki/File:Vaporwave_WP3_Print.jpg",
    "w": 1400,
    "h": 788,
    "bytes": 299804
   },
   "say": "这是一种互联网诞生的美学，把老式计算机图形与希腊雕像融合（不知道为什么），霓虹灯和故障效果结合在一起。",
   "sayAt": "19:04 / 19:15",
   "origin": "在 2009 到 2010 年左右从在线社区中兴起。",
   "usage": "专辑封面、数字拼贴，以及更多实验性广告。",
   "tips": [
    "它既怀旧又非常讽刺，玩弄 80 和 90 年代的消费主义主题"
   ],
   "n": 27
  },
  {
   "slug": "memphis",
   "en": "Memphis",
   "zh": "孟菲斯",
   "group": "digital",
   "t": 580,
   "tc": "9:40",
   "desc": "80 年代意大利的反叛设计：高饱和撞色、几何碎形随意撒、故意\"俗\"的图案，压在黑网格上。",
   "traits": [
    "高饱和撞色",
    "几何碎形",
    "故意失衡",
    "黑网格底"
   ],
   "img": "img/memphis.jpg",
   "thumb": "img/thumbs/memphis.jpg",
   "accent": "#ad71a3",
   "accentInk": "#6b4b66",
   "tint": "#1d171c",
   "tintLight": "#f1d2ec",
   "lum": 0.708,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=580",
   "videoName": "MEMPHIS",
   "ref": {
    "img": "img/pd/memphis.jpg",
    "title": "Memphis-Milano Movement.jpg",
    "artist": "Zanone",
    "license": "CC BY-SA 3.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/3.0",
    "page": "https://commons.wikimedia.org/wiki/File:Memphis-Milano_Movement.jpg",
    "w": 1400,
    "h": 933,
    "bytes": 212478
   },
   "say": "它非常大胆、几何感强、非常有趣，完全是关于后现代的氛围。",
   "sayAt": "09:43 / 09:50",
   "origin": "1980 年代因孟菲斯集团（Memphis Group）而声名鹊起，迅速成为那个时代实验性设计场景的标志。",
   "usage": "复古品牌、编辑作品、需要更多色彩或趣味的设计、非常有趣的包装。",
   "tips": [
    "作者提到 Kittl 里有很多孟菲斯风格的元素和作品"
   ],
   "n": 12
  },
  {
   "slug": "graffiti",
   "en": "Graffiti",
   "zh": "涂鸦",
   "group": "digital",
   "t": 1247,
   "tc": "20:47",
   "desc": "街头的喷漆书写：气泡字与立体字、极粗描边、喷溅与叠涂的肌理、亮到刺眼的撞色。",
   "traits": [
    "气泡·立体字",
    "极粗描边",
    "喷溅肌理",
    "高亮撞色"
   ],
   "img": "img/graffiti.jpg",
   "thumb": "img/thumbs/graffiti.jpg",
   "accent": "#ebdb78",
   "accentInk": "#6b6437",
   "tint": "#1d1c17",
   "tintLight": "#f1edd2",
   "lum": 0.882,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1247",
   "videoName": "GRAFFITI",
   "ref": {
    "img": "img/pd/graffiti.jpg",
    "title": "Berlin Siemensbahn at Siemensstadt asv2021-03 img5.jpg",
    "artist": "A.Savin",
    "license": "FAL",
    "licenseUrl": "http://artlibre.org/licence/lal/en",
    "page": "https://commons.wikimedia.org/wiki/File:Berlin_Siemensbahn_at_Siemensstadt_asv2021-03_img5.jpg",
    "w": 1400,
    "h": 933,
    "bytes": 452568
   },
   "say": "它借鉴了城市街头艺术的趋势，展示大胆的喷漆字母、明亮的色彩、粗糙的纹理、大量的混凝土；充满活力、反叛、充满个性。",
   "sayAt": "20:52 / 21:05",
   "origin": "现代涂鸦艺术在 1960 年代的嘻哈场景中兴起。",
   "usage": "非常前卫的品牌活动、音乐海报、服装品牌，以及那些想要更强街头感的品牌。",
   "tips": [
    "它可能是大多数人已经熟悉的风格"
   ],
   "n": 30
  },
  {
   "slug": "aurora",
   "en": "Aurora",
   "zh": "极光",
   "group": "soft",
   "t": 155,
   "tc": "2:35",
   "desc": "直接向自然借色：青绿到紫红的渐变光带、柔和扩散的光晕、深色背景把光托起来。",
   "traits": [
    "青绿→紫红",
    "发光光带",
    "深底衬托",
    "柔焦扩散"
   ],
   "img": "img/aurora.jpg",
   "thumb": "img/thumbs/aurora.jpg",
   "accent": "#389f78",
   "accentInk": "#266b51",
   "tint": "#171d1b",
   "tintLight": "#d2f1e5",
   "lum": 0.43,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=155",
   "videoName": "AURORA",
   "ref": {
    "img": "img/pd/aurora.jpg",
    "title": "Maardu Northern lights — Estonia, 2022.jpg",
    "artist": "Maxim Bilovitskiy",
    "license": "CC BY 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Maardu_Northern_lights_%E2%80%94_Estonia,_2022.jpg",
    "w": 1400,
    "h": 634,
    "bytes": 74222
   },
   "say": "你可能一直在寻找的就是那种渐变效果，你只是缺少了“极光”这个词。",
   "sayAt": "02:36 / 02:51",
   "origin": "在设计上这种美学更现代，2010 年代真正流行起来——数字艺术家开始使用明亮的颜色和过渡。",
   "usage": "现代品牌、大量 UI/UX 网站，以及更偏宇宙或魔幻风格的数字艺术。",
   "tips": [
    "搜“极光渐变”时加入颗粒或模糊效果，会找到另一种趋势",
    "梦幻渐变的典型配色：紫、粉、蓝、绿"
   ],
   "n": 3
  },
  {
   "slug": "ethereal",
   "en": "Ethereal",
   "zh": "空灵",
   "group": "soft",
   "t": 199,
   "tc": "3:19",
   "desc": "半透明、雾化、若隐若现：低对比、光在雾里散开、主体像浮着——像隔一层薄纱看东西。",
   "traits": [
    "半透明",
    "雾化扩散",
    "低对比",
    "漂浮感"
   ],
   "img": "img/ethereal.jpg",
   "thumb": "img/thumbs/ethereal.jpg",
   "accent": "#875a8c",
   "accentInk": "#67446b",
   "tint": "#1d171d",
   "tintLight": "#eed2f1",
   "lum": 0.382,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=199",
   "videoName": "ETHEREAL",
   "ref": {
    "img": "img/pd/ethereal.jpg",
    "title": "Ethereal landscapes from lost times - Flickr - subarcticmike.jpg",
    "artist": "Mike Beauregard from Canada",
    "license": "CC BY 2.0",
    "licenseUrl": "https://creativecommons.org/licenses/by/2.0",
    "page": "https://commons.wikimedia.org/wiki/File:Ethereal_landscapes_from_lost_times_-_Flickr_-_subarcticmike.jpg",
    "w": 1400,
    "h": 813,
    "bytes": 234354
   },
   "say": "这种风格专注于非常柔和的色调、精致的层次感，和一种轻盈的、超凡脱俗的氛围——就像你走进了一个梦境。",
   "sayAt": "03:21 / 03:56",
   "origin": "空灵美学在艺术史中一直存在，但 2010 年代变得非常流行，尤其是在摄影和网页设计中。",
   "usage": "高端时尚画册、网站首页、概念艺术作品。",
   "tips": [
    "它有点像超现实主义，但比超现实主义更扎根于现实"
   ],
   "n": 4
  },
  {
   "slug": "japandi",
   "en": "Japandi",
   "zh": "日式北欧",
   "group": "soft",
   "t": 540,
   "tc": "9:00",
   "desc": "日本侘寂与北欧极简的交集：米白与木色、低矮家具、亚麻与陶土、克制的留白与秩序。",
   "traits": [
    "米白·木色",
    "低矮家具",
    "亚麻陶土",
    "留白秩序"
   ],
   "img": "img/japandi.jpg",
   "thumb": "img/thumbs/japandi.jpg",
   "accent": "#ebce98",
   "accentInk": "#6b604b",
   "tint": "#1d1b17",
   "tintLight": "#f1e6d2",
   "lum": 0.874,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=540",
   "videoName": "JAPANDI",
   "say": "它是日本极简主义和斯堪的纳维亚温暖的超级美丽结合。",
   "sayAt": "09:07 / 09:17",
   "origin": "2010 年代获得了很大的动力，随着极简主义室内设计的浪潮兴起，现在仍然很流行。",
   "usage": "网站、生活方式产品、品牌，以及（作者见得最多的）海报设计和装饰。",
   "tips": [
    "中性色彩、天然材料，还带一点包豪斯的味道"
   ],
   "n": 11
  },
  {
   "slug": "bohemian",
   "en": "Bohemian",
   "zh": "波西米亚",
   "group": "soft",
   "t": 615,
   "tc": "10:15",
   "desc": "层叠、混搭、手工艺：拱形与地毯纹样、暖土色、植物与藤编，用\"不规则的丰富\"代替整齐。",
   "traits": [
    "暖土色",
    "拱形母题",
    "层叠混搭",
    "手工艺感"
   ],
   "img": "img/bohemian.jpg",
   "thumb": "img/thumbs/bohemian.jpg",
   "accent": "#d28960",
   "accentInk": "#6b4631",
   "tint": "#1d1917",
   "tintLight": "#f1ddd2",
   "lum": 0.841,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=615",
   "videoName": "BOHEMIAN",
   "say": "它的特点是融合了全球影响，带有层次感的纹理，更偏向大地色调；它非常随性、自由奔放，给人一种世界旅行的感觉。",
   "sayAt": "10:24 / 10:29",
   "origin": "起源于 19 世纪的艺术家社区，并在 1960 年代进入主流。",
   "usage": "活动品牌、时尚系列，以及那些拥抱旅行和创造力的生活方式产品。",
   "tips": [
    "这种风格实现起来很容易：选对字体和元素就行，时间主要花在找合适的调色板上"
   ],
   "n": 13
  },
  {
   "slug": "shabby-chic",
   "en": "Shabby Chic",
   "zh": "复古做旧",
   "group": "soft",
   "t": 660,
   "tc": "11:00",
   "desc": "故意磨损的优雅：褪色的印花、做旧白漆、蕾丝与玫瑰，整体罩一层柔粉。",
   "traits": [
    "褪色印花",
    "做旧白漆",
    "蕾丝玫瑰",
    "柔粉罩色"
   ],
   "img": "img/shabby-chic.jpg",
   "thumb": "img/thumbs/shabby-chic.jpg",
   "accent": "#eb98be",
   "accentInk": "#6b4b5a",
   "tint": "#1d171a",
   "tintLight": "#f1d2e0",
   "lum": 0.935,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=660",
   "videoName": "SHABBY CHIC",
   "ref": {
    "img": "img/pd/shabby-chic.jpg",
    "title": "Shabby chic coffee table.jpg",
    "artist": "Slothedit",
    "license": "CC0",
    "licenseUrl": "http://creativecommons.org/publicdomain/zero/1.0/deed.en",
    "page": "https://commons.wikimedia.org/wiki/File:Shabby_chic_coffee_table.jpg",
    "w": 1400,
    "h": 700,
    "bytes": 229092
   },
   "say": "如果你喜欢做旧效果和柔和的色调、带有复古浪漫感，那么这种风格就是你要找的。",
   "sayAt": "11:00 / 11:08",
   "origin": "1980、90 年代作为室内设计趋势兴起。",
   "usage": "婚礼请柬、非常舒适的包装设计、产品品牌，以及那些想要温馨怀旧外观的公司品牌。",
   "tips": [
    "典型元素：褪色的花卉图案、重新利用的家具"
   ],
   "n": 14
  },
  {
   "slug": "farmhouse",
   "en": "Farmhouse",
   "zh": "农舍",
   "group": "soft",
   "t": 688,
   "tc": "11:28",
   "desc": "乡村田园的朴素：奶油底、手绘小插图（蘑菇、搪瓷壶、小木屋）、旧式字体做标题。",
   "traits": [
    "奶油底",
    "手绘插图",
    "木与搪瓷",
    "旧式字体"
   ],
   "img": "img/farmhouse.jpg",
   "thumb": "img/thumbs/farmhouse.jpg",
   "accent": "#dcbe8f",
   "accentInk": "#6b5f4b",
   "tint": "#1d1b17",
   "tintLight": "#f1e5d2",
   "lum": 0.916,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=688",
   "videoName": "FARMHOUSE",
   "ref": {
    "img": "img/pd/farmhouse.jpg",
    "title": "Waldstatt Brunnhalden 25.jpg",
    "artist": "Zivilschutz KGS AR",
    "license": "CC BY-SA 4.0",
    "licenseUrl": "https://creativecommons.org/licenses/by-sa/4.0",
    "page": "https://commons.wikimedia.org/wiki/File:Waldstatt_Brunnhalden_25.jpg",
    "w": 1400,
    "h": 788,
    "bytes": 386704
   },
   "say": "它更注重乡村的简约、天然面料，以及迷人的乡村美学，扎根于更乡村的环境中。",
   "sayAt": "11:41 / 11:46",
   "origin": "2010 年代通过社交媒体流行起来，并一直持续到现在。",
   "usage": "家居装饰品牌、精品和服装品牌、以自然为主题的书籍封面，以及任何旨在营造温暖怀旧氛围的设计。",
   "tips": [
    "常与 Cottagecore 相提并论，两者都是 Pinterest 上搜“设计/图形”的好关键词"
   ],
   "n": 15
  },
  {
   "slug": "kawaii",
   "en": "Kawaii",
   "zh": "可爱",
   "group": "soft",
   "t": 1521,
   "tc": "25:21",
   "desc": "把\"可爱\"当成核心策略：圆润到没有棱角的造型、粉彩色、小动物与甜点、绝对无害的表情。",
   "traits": [
    "圆润造型",
    "粉彩色",
    "小动物甜点",
    "无害表情"
   ],
   "img": "img/kawaii.jpg",
   "thumb": "img/thumbs/kawaii.jpg",
   "accent": "#9f80e7",
   "accentInk": "#4a3b6b",
   "tint": "#19171d",
   "tintLight": "#dbd2f1",
   "lum": 0.647,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1521",
   "videoName": "KAWAII",
   "say": "卡哇伊是日本“可爱”的概念，它采用圆润的形状、柔和的色彩和可爱的卡通角色，给人一种类似儿童卡通的感觉。",
   "sayAt": "25:23 / 25:26",
   "origin": "1970 年代在日本流行文化中兴起，如今已经席卷了全球时尚、文具和媒体。",
   "usage": "角色品牌、玩具包装、服装、社交媒体图形。",
   "tips": [
    "看板元素是圆润造型 + 柔和色彩 + 可爱的角色"
   ],
   "n": 36
  },
  {
   "slug": "coquette",
   "en": "Coquette",
   "zh": "娇媚",
   "group": "soft",
   "t": 1567,
   "tc": "26:07",
   "desc": "丝带、蕾丝与柔粉的女性化甜美：粉与酒红、蝴蝶结、蕾丝纹理、手写体花字。",
   "traits": [
    "粉·酒红",
    "蝴蝶结",
    "蕾丝纹理",
    "手写花字"
   ],
   "img": "img/coquette.jpg",
   "thumb": "img/thumbs/coquette.jpg",
   "accent": "#be7c9c",
   "accentInk": "#6b4658",
   "tint": "#1d171a",
   "tintLight": "#f1d2e1",
   "lum": 0.819,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1567",
   "videoName": "Coquette",
   "say": "它采用柔和浪漫的美学，带有精致的花卉图案、柔和的色调和一种俏皮的氛围。",
   "sayAt": "26:11 / 26:25",
   "origin": "它借鉴了历史时尚，比如洛可可风格，给人一种维多利亚时代的蕾丝感；如今我们看到这种风格的现代复兴。",
   "usage": "精品品牌、女性向风格、编辑排版，以及美容和时尚系列的包装。",
   "tips": [
    "想象蕾丝、丝带、柔和的轮廓——说实话，它有点像情人节的东西"
   ],
   "n": 37
  },
  {
   "slug": "scrapbook",
   "en": "Bonus Style — Scrapbook",
   "zh": "拼贴手账（加映）",
   "group": "bonus",
   "t": 1715,
   "tc": "28:35",
   "desc": "视频结尾额外给的风格：拍立得照片、纸胶带、手写标注、剪纸字母一层层贴起来，私人且手工。",
   "traits": [
    "拍立得照片",
    "纸胶带·剪纸",
    "手写标注",
    "层叠拼贴"
   ],
   "img": "img/scrapbook.jpg",
   "thumb": "img/thumbs/scrapbook.jpg",
   "accent": "#c6b781",
   "accentInk": "#6b644b",
   "tint": "#1d1c17",
   "tintLight": "#f1ead2",
   "lum": 0.751,
   "videoUrl": "https://www.bilibili.com/video/BV1anQwYZEw2?t=1715",
   "videoName": "SCRAPBOOK COLLAGE",
   "say": "这种风格将照片、剪贴文字、分层装饰元素拼贴在一起，给人一种手工制作的模拟感。",
   "sayAt": "28:37 / 28:48",
   "origin": "剪贴簿显然已经存在很长时间，但拼贴在 20 世纪得到了显著的推动，并一直是一种受欢迎的艺术形式。",
   "usage": "个人日记、婚礼请柬、品牌活动、愿景板、社交媒体帖子。",
   "tips": [
    "作者原话：这严格来说是第 41 种风格，“但听起来不如 40 那么好”，所以作为额外赠送"
   ],
   "n": 41
  }
 ]
};
